INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            10, 
            'Counter-Strike', 
            'Valve', 
            'Valve', 
            NULL, 
            234220, 
            6172, 
            0, 
            '10,000,000 .. 20,000,000', 
            15339, 
            2792, 
            209, 
            117, 
            9.99, 
            9.99, 
            0, 
            10444);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            60, 
            'Ricochet', 
            'Valve', 
            'Valve', 
            NULL, 
            4755, 
            1011, 
            0, 
            '5,000,000 .. 10,000,000', 
            87, 
            0, 
            3, 
            0, 
            4.99, 
            4.99, 
            0, 
            6);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            70, 
            'Half-Life', 
            'Valve', 
            'Valve', 
            NULL, 
            127869, 
            4592, 
            0, 
            '10,000,000 .. 20,000,000', 
            685, 
            297, 
            118, 
            207, 
            9.99, 
            9.99, 
            0, 
            798);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            240, 
            'Counter-Strike: Source', 
            'Valve', 
            'Valve', 
            NULL, 
            167748, 
            6457, 
            0, 
            '10,000,000 .. 20,000,000', 
            7071, 
            30, 
            447, 
            30, 
            9.99, 
            9.99, 
            0, 
            8515);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            320, 
            'Half-Life 2: Deathmatch', 
            'Valve', 
            'Valve', 
            NULL, 
            11873, 
            1204, 
            0, 
            '10,000,000 .. 20,000,000', 
            238, 
            0, 
            61, 
            0, 
            4.99, 
            4.99, 
            0, 
            125);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            340, 
            'Half-Life 2: Lost Coast', 
            'Valve', 
            'Valve', 
            NULL, 
            12072, 
            1452, 
            0, 
            '20,000,000 .. 50,000,000', 
            399, 
            1, 
            28, 
            1, 
            0.00, 
            0.00, 
            0, 
            15);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            400, 
            'Portal', 
            'Valve', 
            'Valve', 
            NULL, 
            161353, 
            2507, 
            0, 
            '10,000,000 .. 20,000,000', 
            277, 
            62, 
            152, 
            99, 
            9.99, 
            9.99, 
            0, 
            437);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            440, 
            'Team Fortress 2', 
            'Valve', 
            'Valve', 
            NULL, 
            979250, 
            137124, 
            0, 
            '50,000,000 .. 100,000,000', 
            11696, 
            707, 
            388, 
            375, 
            0.00, 
            0.00, 
            0, 
            58080);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            550, 
            'Left 4 Dead 2', 
            'Valve', 
            'Valve', 
            NULL, 
            862280, 
            22021, 
            0, 
            '50,000,000 .. 100,000,000', 
            2165, 
            290, 
            483, 
            98, 
            9.99, 
            9.99, 
            0, 
            23668);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            570, 
            'Dota 2', 
            'Valve', 
            'Valve', 
            NULL, 
            1887652, 
            424153, 
            0, 
            '200,000,000 .. 500,000,000', 
            44237, 
            1578, 
            931, 
            508, 
            0.00, 
            0.00, 
            0, 
            572276);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            620, 
            'Portal 2', 
            'Valve', 
            'Valve', 
            NULL, 
            399636, 
            5281, 
            0, 
            '10,000,000 .. 20,000,000', 
            963, 
            147, 
            506, 
            213, 
            1.99, 
            1.99, 
            0, 
            1582);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            730, 
            'Counter-Strike: Global Offensive', 
            'Valve', 
            'Valve', 
            NULL, 
            7216172, 
            1068690, 
            0, 
            '100,000,000 .. 200,000,000', 
            32064, 
            749, 
            5386, 
            297, 
            0.00, 
            0.00, 
            0, 
            1298156);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            4000, 
            'Garry''s Mod', 
            'Facepunch Studios', 
            'Valve', 
            NULL, 
            1061107, 
            35756, 
            0, 
            '20,000,000 .. 50,000,000', 
            8115, 
            156, 
            1319, 
            129, 
            9.99, 
            9.99, 
            0, 
            20451);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            49520, 
            'Borderlands 2', 
            'Gearbox Software, Aspyr (Mac), Aspyr (Linux)', 
            '2K, Aspyr (Mac), Aspyr (Linux)', 
            NULL, 
            268438, 
            17421, 
            0, 
            '10,000,000 .. 20,000,000', 
            3210, 
            429, 
            970, 
            267, 
            19.99, 
            19.99, 
            0, 
            7128);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            72850, 
            'The Elder Scrolls V: Skyrim', 
            'Bethesda Game Studios', 
            'Bethesda Softworks', 
            NULL, 
            299929, 
            16273, 
            0, 
            '5,000,000 .. 10,000,000', 
            7613, 
            217, 
            3673, 
            375, 
            19.99, 
            19.99, 
            0, 
            1796);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            96000, 
            'The Tiny Bang Story', 
            'Colibri Games', 
            'Colibri Games', 
            NULL, 
            5546, 
            796, 
            0, 
            '5,000,000 .. 10,000,000', 
            314, 
            0, 
            309, 
            0, 
            4.99, 
            4.99, 
            0, 
            11);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            105600, 
            'Terraria', 
            'Re-Logic', 
            'Re-Logic', 
            NULL, 
            1294726, 
            32726, 
            0, 
            '20,000,000 .. 50,000,000', 
            7520, 
            333, 
            2102, 
            198, 
            9.99, 
            9.99, 
            0, 
            25585);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            107410, 
            'Arma 3', 
            'Bohemia Interactive', 
            'Bohemia Interactive', 
            NULL, 
            245163, 
            26079, 
            0, 
            '5,000,000 .. 10,000,000', 
            11373, 
            523, 
            965, 
            133, 
            29.99, 
            29.99, 
            0, 
            9359);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            108600, 
            'Project Zomboid', 
            'The Indie Stone', 
            'The Indie Stone', 
            NULL, 
            298617, 
            18484, 
            0, 
            '10,000,000 .. 20,000,000', 
            3983, 
            808, 
            896, 
            123, 
            19.99, 
            19.99, 
            0, 
            25139);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            204360, 
            'Castle Crashers', 
            'The Behemoth', 
            'The Behemoth', 
            NULL, 
            112820, 
            4537, 
            0, 
            '5,000,000 .. 10,000,000', 
            541, 
            198, 
            285, 
            324, 
            14.99, 
            14.99, 
            0, 
            1214);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            218230, 
            'PlanetSide 2', 
            'Rogue Planet Games', 
            'Daybreak Game Company', 
            NULL, 
            58451, 
            13683, 
            0, 
            '5,000,000 .. 10,000,000', 
            992, 
            0, 
            105, 
            0, 
            0.00, 
            0.00, 
            0, 
            841);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            218620, 
            'PAYDAY 2', 
            'OVERKILL - a Starbreeze Studio.', 
            'Starbreeze Publishing AB', 
            NULL, 
            588101, 
            68708, 
            0, 
            '20,000,000 .. 50,000,000', 
            10010, 
            5082, 
            602, 
            1526, 
            9.99, 
            9.99, 
            0, 
            17573);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            221100, 
            'DayZ', 
            'Bohemia Interactive', 
            'Bohemia Interactive', 
            NULL, 
            303484, 
            95934, 
            0, 
            '5,000,000 .. 10,000,000', 
            12730, 
            756, 
            2511, 
            243, 
            49.99, 
            49.99, 
            0, 
            32241);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            227300, 
            'Euro Truck Simulator 2', 
            'SCS Software', 
            'SCS Software', 
            NULL, 
            773780, 
            20767, 
            0, 
            '10,000,000 .. 20,000,000', 
            8096, 
            260, 
            1812, 
            70, 
            19.99, 
            19.99, 
            0, 
            30600);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            227940, 
            'Heroes & Generals', 
            'TLM Partners', 
            'TLM Partners', 
            NULL, 
            96709, 
            46693, 
            0, 
            '10,000,000 .. 20,000,000', 
            4577, 
            0, 
            77, 
            0, 
            0.00, 
            0.00, 
            0, 
            4);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            230410, 
            'Warframe', 
            'Digital Extremes', 
            'Digital Extremes', 
            NULL, 
            517185, 
            78575, 
            0, 
            '20,000,000 .. 50,000,000', 
            11179, 
            692, 
            436, 
            275, 
            0.00, 
            0.00, 
            0, 
            50869);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            236390, 
            'War Thunder', 
            'Gaijin Entertainment', 
            'Gaijin Network Ltd', 
            NULL, 
            417682, 
            249300, 
            0, 
            '20,000,000 .. 50,000,000', 
            8899, 
            763, 
            435, 
            252, 
            0.00, 
            0.00, 
            0, 
            73133);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            238960, 
            'Path of Exile', 
            'Grinding Gear Games', 
            'Grinding Gear Games', 
            NULL, 
            201265, 
            24367, 
            0, 
            '20,000,000 .. 50,000,000', 
            10659, 
            947, 
            458, 
            371, 
            0.00, 
            0.00, 
            0, 
            42258);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            239140, 
            'Dying Light', 
            'Techland', 
            'Techland', 
            NULL, 
            406753, 
            20616, 
            0, 
            '10,000,000 .. 20,000,000', 
            2137, 
            277, 
            1103, 
            134, 
            19.99, 
            19.99, 
            0, 
            13512);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            242760, 
            'The Forest', 
            'Endnight Games Ltd', 
            'Endnight Games Ltd', 
            NULL, 
            531344, 
            25015, 
            0, 
            '20,000,000 .. 50,000,000', 
            1390, 
            204, 
            842, 
            204, 
            19.99, 
            19.99, 
            0, 
            5125);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            251570, 
            '7 Days to Die', 
            'The Fun Pimps', 
            'The Fun Pimps Entertainment LLC', 
            NULL, 
            297048, 
            39790, 
            0, 
            '10,000,000 .. 20,000,000', 
            5835, 
            659, 
            1070, 
            290, 
            44.99, 
            44.99, 
            0, 
            49620);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            252490, 
            'Rust', 
            'Facepunch Studios', 
            'Facepunch Studios', 
            NULL, 
            959037, 
            142290, 
            0, 
            '20,000,000 .. 50,000,000', 
            21021, 
            1072, 
            2749, 
            243, 
            39.99, 
            39.99, 
            0, 
            71552);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            252950, 
            'Rocket League', 
            'Psyonix LLC', 
            'Psyonix LLC', 
            NULL, 
            508523, 
            71421, 
            0, 
            '10,000,000 .. 20,000,000', 
            18750, 
            364, 
            3129, 
            135, 
            0.00, 
            0.00, 
            0, 
            22796);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            255710, 
            'Cities: Skylines', 
            'Colossal Order Ltd.', 
            'Paradox Interactive', 
            NULL, 
            242511, 
            17470, 
            0, 
            '5,000,000 .. 10,000,000', 
            3189, 
            18, 
            649, 
            19, 
            29.99, 
            29.99, 
            0, 
            10682);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            261550, 
            'Mount & Blade II: Bannerlord', 
            'TaleWorlds Entertainment', 
            'TaleWorlds Entertainment', 
            NULL, 
            219314, 
            30161, 
            0, 
            '10,000,000 .. 20,000,000', 
            8682, 
            521, 
            3327, 
            429, 
            49.99, 
            49.99, 
            0, 
            20762);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            271590, 
            'Grand Theft Auto V', 
            'Rockstar North', 
            'Rockstar Games', 
            NULL, 
            1622483, 
            240811, 
            0, 
            '50,000,000 .. 100,000,000', 
            12419, 
            1069, 
            5636, 
            161, 
            14.80, 
            14.80, 
            0, 
            138593);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            272060, 
            'Serena', 
            'Senscape', 
            'Senscape', 
            NULL, 
            4917, 
            1466, 
            0, 
            '10,000,000 .. 20,000,000', 
            71, 
            0, 
            3, 
            0, 
            0.00, 
            0.00, 
            0, 
            2);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            275850, 
            'No Man''s Sky', 
            'Hello Games', 
            'Hello Games', 
            NULL, 
            256240, 
            58772, 
            0, 
            '5,000,000 .. 10,000,000', 
            2918, 
            806, 
            1032, 
            104, 
            23.99, 
            59.99, 
            60, 
            12855);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            289070, 
            'Sid Meier’s Civilization VI', 
            'Firaxis Games, Aspyr (Mac), Aspyr (Linux)', 
            '2K, Aspyr (Mac), Aspyr (Linux)', 
            NULL, 
            282080, 
            44372, 
            0, 
            '5,000,000 .. 10,000,000', 
            5190, 
            609, 
            1417, 
            155, 
            59.99, 
            59.99, 
            0, 
            65878);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            291480, 
            'Warface', 
            'MY.GAMES', 
            'MY.GAMES', 
            NULL, 
            54864, 
            27558, 
            0, 
            '10,000,000 .. 20,000,000', 
            839, 
            0, 
            85, 
            0, 
            0.00, 
            0.00, 
            0, 
            403);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            291550, 
            'Brawlhalla', 
            'Blue Mammoth Games', 
            'Ubisoft', 
            NULL, 
            304919, 
            66310, 
            0, 
            '20,000,000 .. 50,000,000', 
            4831, 
            285, 
            174, 
            98, 
            0.00, 
            0.00, 
            0, 
            13269);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            292030, 
            'The Witcher 3: Wild Hunt', 
            'CD PROJEKT RED', 
            'CD PROJEKT RED', 
            NULL, 
            763464, 
            31184, 
            0, 
            '10,000,000 .. 20,000,000', 
            3619, 
            938, 
            1116, 
            277, 
            39.99, 
            39.99, 
            0, 
            17465);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            301520, 
            'Robocraft', 
            'Freejam', 
            'Freejam', 
            NULL, 
            86480, 
            32014, 
            0, 
            '10,000,000 .. 20,000,000', 
            6093, 
            0, 
            254, 
            0, 
            0.00, 
            0.00, 
            0, 
            109);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            304050, 
            'Trove', 
            'gamigo US Inc.', 
            'gamigo US Inc.', 
            NULL, 
            73956, 
            18092, 
            0, 
            '10,000,000 .. 20,000,000', 
            6819, 
            1580, 
            233, 
            1580, 
            0.00, 
            0.00, 
            0, 
            950);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            304930, 
            'Unturned', 
            'Smartly Dressed Games', 
            'Smartly Dressed Games', 
            NULL, 
            498957, 
            46519, 
            0, 
            '50,000,000 .. 100,000,000', 
            8157, 
            809, 
            338, 
            322, 
            0.00, 
            0.00, 
            0, 
            22741);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            322330, 
            'Don''t Starve Together', 
            'Klei Entertainment', 
            'Klei Entertainment', 
            NULL, 
            445562, 
            20228, 
            0, 
            '20,000,000 .. 50,000,000', 
            2903, 
            414, 
            554, 
            111, 
            14.99, 
            14.99, 
            0, 
            36367);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            346110, 
            'ARK: Survival Evolved', 
            'Studio Wildcard, Instinct Games, Efecto Studios, Virtual Basement LLC', 
            'Studio Wildcard, Snail Games USA', 
            NULL, 
            585245, 
            116231, 
            0, 
            '20,000,000 .. 50,000,000', 
            8196, 
            313, 
            957, 
            214, 
            14.99, 
            14.99, 
            0, 
            28964);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            359550, 
            'Tom Clancy''s Rainbow Six Siege', 
            'Ubisoft Montreal', 
            'Ubisoft', 
            NULL, 
            1116203, 
            200856, 
            0, 
            '20,000,000 .. 50,000,000', 
            13663, 
            471, 
            2553, 
            125, 
            19.99, 
            19.99, 
            0, 
            60498);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            367520, 
            'Hollow Knight', 
            'Team Cherry', 
            'Team Cherry', 
            NULL, 
            357250, 
            10624, 
            0, 
            '10,000,000 .. 20,000,000', 
            1860, 
            62, 
            662, 
            84, 
            14.99, 
            14.99, 
            0, 
            5845);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            377160, 
            'Fallout 4', 
            'Bethesda Game Studios', 
            'Bethesda Softworks', 
            NULL, 
            311319, 
            64962, 
            0, 
            '10,000,000 .. 20,000,000', 
            5486, 
            277, 
            2973, 
            49, 
            19.99, 
            19.99, 
            0, 
            18855);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            381210, 
            'Dead by Daylight', 
            'Behaviour Interactive Inc.', 
            'Behaviour Interactive Inc.', 
            NULL, 
            598385, 
            145930, 
            0, 
            '20,000,000 .. 50,000,000', 
            10543, 
            605, 
            1599, 
            275, 
            19.99, 
            19.99, 
            0, 
            44769);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            386360, 
            'SMITE', 
            'Titan Forge Games', 
            'Hi-Rez Studios', 
            NULL, 
            93597, 
            24936, 
            0, 
            '10,000,000 .. 20,000,000', 
            11068, 
            127, 
            208, 
            106, 
            0.00, 
            0.00, 
            0, 
            7562);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            413150, 
            'Stardew Valley', 
            'ConcernedApe', 
            'ConcernedApe', 
            NULL, 
            739657, 
            12658, 
            0, 
            '10,000,000 .. 20,000,000', 
            4503, 
            396, 
            1870, 
            251, 
            14.99, 
            14.99, 
            0, 
            73592);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            417910, 
            'Street Warriors Online', 
            'Crazy Rocks Studios', 
            'Crazy Rocks Studios', 
            NULL, 
            953, 
            691, 
            0, 
            '10,000,000 .. 20,000,000', 
            70, 
            0, 
            34, 
            0, 
            1.99, 
            1.99, 
            0, 
            0);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            431960, 
            'Wallpaper Engine', 
            'Wallpaper Engine Team', 
            'Wallpaper Engine Team', 
            NULL, 
            798625, 
            15902, 
            0, 
            '20,000,000 .. 50,000,000', 
            3468, 
            106, 
            976, 
            6, 
            3.99, 
            3.99, 
            0, 
            116923);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            433850, 
            'Z1 Battle Royale', 
            'Daybreak Game Company', 
            'Daybreak Game Company', 
            NULL, 
            114147, 
            90909, 
            0, 
            '10,000,000 .. 20,000,000', 
            3109, 
            0, 
            144, 
            0, 
            0.00, 
            0.00, 
            0, 
            534);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            438100, 
            'VRChat', 
            'VRChat Inc.', 
            'VRChat Inc.', 
            NULL, 
            168120, 
            56181, 
            0, 
            '10,000,000 .. 20,000,000', 
            3483, 
            981, 
            137, 
            198, 
            0.00, 
            0.00, 
            0, 
            34116);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            444090, 
            'Paladins', 
            'Evil Mojo Games', 
            'Hi-Rez Studios', 
            NULL, 
            293485, 
            51815, 
            0, 
            '10,000,000 .. 20,000,000', 
            6218, 
            1935, 
            551, 
            3842, 
            0.00, 
            0.00, 
            0, 
            3375);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            444200, 
            'World of Tanks Blitz', 
            'Wargaming Group Limited', 
            'Wargaming Group Limited', 
            NULL, 
            113010, 
            29246, 
            0, 
            '10,000,000 .. 20,000,000', 
            13238, 
            530, 
            264, 
            604, 
            0.00, 
            0.00, 
            0, 
            10784);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            477160, 
            'Human Fall Flat', 
            'No Brakes Games', 
            'Curve Games', 
            NULL, 
            192421, 
            10731, 
            0, 
            '10,000,000 .. 20,000,000', 
            642, 
            18, 
            404, 
            27, 
            19.99, 
            19.99, 
            0, 
            2342);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            532210, 
            'Life is Strange 2', 
            'DONTNOD Entertainment, Feral Interactive (Mac), Feral Interactive (Linux)', 
            'Square Enix, Feral Interactive (Mac), Feral Interactive (Linux)', 
            NULL, 
            28849, 
            4800, 
            0, 
            '10,000,000 .. 20,000,000', 
            409, 
            0, 
            194, 
            0, 
            31.96, 
            31.96, 
            0, 
            266);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            550650, 
            'Black Squad', 
            'VALOFE, NS STUDIO', 
            'VALOFE', 
            NULL, 
            62030, 
            19534, 
            0, 
            '10,000,000 .. 20,000,000', 
            5222, 
            46, 
            64, 
            46, 
            0.00, 
            0.00, 
            0, 
            420);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            552990, 
            'World of Warships', 
            'Wargaming Group Limited', 
            'Wargaming Group Limited', 
            NULL, 
            110145, 
            31983, 
            0, 
            '10,000,000 .. 20,000,000', 
            1830, 
            230, 
            201, 
            344, 
            0.00, 
            0.00, 
            0, 
            9841);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            553850, 
            'HELLDIVERS 2', 
            'Arrowhead Game Studios', 
            'PlayStation Publishing LLC', 
            NULL, 
            641382, 
            259994, 
            0, 
            '50,000,000 .. 100,000,000', 
            3228, 
            226, 
            2266, 
            98, 
            39.99, 
            39.99, 
            0, 
            18779);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            578080, 
            'PUBG: BATTLEGROUNDS', 
            'KRAFTON, Inc.', 
            'KRAFTON, Inc.', 
            NULL, 
            1422693, 
            1000004, 
            0, 
            '50,000,000 .. 100,000,000', 
            22973, 
            776, 
            6493, 
            347, 
            0.00, 
            0.00, 
            0, 
            599441);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            582010, 
            'Monster Hunter: World', 
            'CAPCOM Co., Ltd.', 
            'CAPCOM Co., Ltd.', 
            NULL, 
            400074, 
            56860, 
            0, 
            '10,000,000 .. 20,000,000', 
            8648, 
            445, 
            3205, 
            285, 
            29.99, 
            29.99, 
            0, 
            56918);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            594650, 
            'Hunt: Showdown 1896', 
            'Crytek', 
            'Crytek', 
            NULL, 
            168956, 
            57991, 
            0, 
            '10,000,000 .. 20,000,000', 
            12145, 
            1118, 
            1109, 
            930, 
            29.99, 
            29.99, 
            0, 
            20686);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            632360, 
            'Risk of Rain 2', 
            'Hopoo Games', 
            'Gearbox Publishing', 
            NULL, 
            271665, 
            18628, 
            0, 
            '5,000,000 .. 10,000,000', 
            2756, 
            588, 
            942, 
            280, 
            8.24, 
            24.99, 
            67, 
            28678);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            648800, 
            'Raft', 
            'Redbeet Interactive', 
            'Axolot Games', 
            NULL, 
            301526, 
            21058, 
            0, 
            '10,000,000 .. 20,000,000', 
            1518, 
            79, 
            834, 
            79, 
            19.99, 
            19.99, 
            0, 
            8130);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            739630, 
            'Phasmophobia', 
            'Kinetic Games', 
            'Kinetic Games', 
            NULL, 
            676179, 
            28726, 
            0, 
            '10,000,000 .. 20,000,000', 
            2352, 
            291, 
            995, 
            139, 
            13.99, 
            13.99, 
            0, 
            16130);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            755790, 
            'Ring of Elysium', 
            'Aurora Studio', 
            'TCH Scarlet Limited', 
            NULL, 
            74672, 
            25722, 
            0, 
            '10,000,000 .. 20,000,000', 
            609, 
            0, 
            110, 
            0, 
            0.00, 
            0.00, 
            0, 
            5);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            814380, 
            'Sekiro: Shadows Die Twice - GOTY Edition', 
            'FromSoftware, Inc.', 
            'Activision (Excluding Japan and Asia), FromSoftware, Inc. (Japan), 方块游戏 (Asia)', 
            NULL, 
            282697, 
            13794, 
            0, 
            '10,000,000 .. 20,000,000', 
            2790, 
            150, 
            1841, 
            50, 
            59.99, 
            59.99, 
            0, 
            11254);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            892970, 
            'Valheim', 
            'Iron Gate AB', 
            'Coffee Stain Publishing', 
            NULL, 
            439098, 
            25903, 
            0, 
            '20,000,000 .. 50,000,000', 
            3961, 
            665, 
            1545, 
            146, 
            19.99, 
            19.99, 
            0, 
            19684);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            899770, 
            'Last Epoch', 
            'Eleventh Hour Games', 
            'Eleventh Hour Games', 
            NULL, 
            75465, 
            22564, 
            0, 
            '20,000,000 .. 50,000,000', 
            5014, 
            0, 
            3125, 
            0, 
            34.99, 
            34.99, 
            0, 
            2693);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            901583, 
            'Grand Theft Auto IV: Complete Edition', 
            'Rockstar North, Rockstar Toronto', 
            'Rockstar Games', 
            NULL, 
            131295, 
            29133, 
            0, 
            '20,000,000 .. 50,000,000', 
            0, 
            0, 
            0, 
            0, 
            0.00, 
            0.00, 
            0, 
            0);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            945360, 
            'Among Us', 
            'Innersloth', 
            'Innersloth', 
            NULL, 
            632488, 
            56529, 
            0, 
            '20,000,000 .. 50,000,000', 
            1283, 
            70, 
            688, 
            69, 
            4.99, 
            4.99, 
            0, 
            5801);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            990080, 
            'Hogwarts Legacy', 
            'Avalanche Software', 
            'Warner Bros. Games', 
            NULL, 
            253251, 
            25864, 
            0, 
            '10,000,000 .. 20,000,000', 
            2346, 
            326, 
            1913, 
            185, 
            17.99, 
            59.99, 
            70, 
            23776);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            1046930, 
            'Dota Underlords', 
            'Valve', 
            'Valve', 
            NULL, 
            74626, 
            16126, 
            0, 
            '5,000,000 .. 10,000,000', 
            2138, 
            40, 
            226, 
            54, 
            0.00, 
            0.00, 
            0, 
            1444);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            1063730, 
            'New World', 
            'Amazon Games', 
            'Amazon Games', 
            NULL, 
            191630, 
            88337, 
            0, 
            '50,000,000 .. 100,000,000', 
            8213, 
            425, 
            3996, 
            621, 
            39.99, 
            39.99, 
            0, 
            3645);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            1085660, 
            'Destiny 2', 
            'Bungie', 
            'Bungie', 
            NULL, 
            490349, 
            120594, 
            0, 
            '20,000,000 .. 50,000,000', 
            12181, 
            738, 
            363, 
            271, 
            0.00, 
            0.00, 
            0, 
            28507);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            1086940, 
            'Baldur''s Gate 3', 
            'Larian Studios', 
            'Larian Studios', 
            NULL, 
            626835, 
            20696, 
            0, 
            '20,000,000 .. 50,000,000', 
            6407, 
            534, 
            3910, 
            357, 
            59.99, 
            59.99, 
            0, 
            85109);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            1089350, 
            'NBA 2K20', 
            'Visual Concepts', 
            '2K', 
            NULL, 
            30361, 
            30448, 
            0, 
            '5,000,000 .. 10,000,000', 
            9031, 
            0, 
            2396, 
            0, 
            0.00, 
            0.00, 
            0, 
            461);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            1091500, 
            'Cyberpunk 2077', 
            'CD PROJEKT RED', 
            'CD PROJEKT RED', 
            NULL, 
            632615, 
            132892, 
            0, 
            '20,000,000 .. 50,000,000', 
            4743, 
            237, 
            3334, 
            88, 
            59.99, 
            59.99, 
            0, 
            26950);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            1097150, 
            'Fall Guys: Ultimate Knockout', 
            'Mediatonic', 
            'Ravenscourt', 
            NULL, 
            387213, 
            89255, 
            0, 
            '20,000,000 .. 50,000,000', 
            1405, 
            124, 
            621, 
            99, 
            0.00, 
            0.00, 
            0, 
            1841);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            1172470, 
            'Apex Legends', 
            'Respawn', 
            'Electronic Arts', 
            NULL, 
            646714, 
            295571, 
            0, 
            '50,000,000 .. 100,000,000', 
            8760, 
            413, 
            758, 
            181, 
            0.00, 
            0.00, 
            0, 
            217195);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            1174180, 
            'Red Dead Redemption 2', 
            'Rockstar Games', 
            'Rockstar Games', 
            NULL, 
            561059, 
            51201, 
            0, 
            '10,000,000 .. 20,000,000', 
            4039, 
            298, 
            2291, 
            146, 
            23.99, 
            59.99, 
            60, 
            32349);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            1203220, 
            'NARAKA: BLADEPOINT', 
            '24 Entertainment', 
            'NetEase Games Global', 
            NULL, 
            203336, 
            87994, 
            0, 
            '20,000,000 .. 50,000,000', 
            6561, 
            584, 
            492, 
            286, 
            0.00, 
            0.00, 
            0, 
            290989);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            1222670, 
            'The Sims 4', 
            'Maxis', 
            'Electronic Arts', 
            NULL, 
            129729, 
            18606, 
            0, 
            '10,000,000 .. 20,000,000', 
            990, 
            751, 
            235, 
            67, 
            0.00, 
            0.00, 
            0, 
            31359);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            1238810, 
            'Battlefield V', 
            'DICE', 
            'Electronic Arts', 
            NULL, 
            158727, 
            65932, 
            0, 
            '5,000,000 .. 10,000,000', 
            1832, 
            213, 
            711, 
            71, 
            49.99, 
            49.99, 
            0, 
            25562);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            1240440, 
            'Halo Infinite', 
            '343 Industries', 
            'Xbox Game Studios', 
            NULL, 
            121491, 
            51741, 
            0, 
            '10,000,000 .. 20,000,000', 
            1489, 
            25, 
            134, 
            27, 
            0.00, 
            0.00, 
            0, 
            3311);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            1245620, 
            'ELDEN RING', 
            'FromSoftware, Inc.', 
            'FromSoftware, Inc., Bandai Namco Entertainment', 
            NULL, 
            885155, 
            69407, 
            0, 
            '20,000,000 .. 50,000,000', 
            8217, 
            574, 
            5563, 
            120, 
            59.99, 
            59.99, 
            0, 
            53953);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            1326470, 
            'Sons Of The Forest', 
            'Endnight Games Ltd', 
            'Newnight', 
            NULL, 
            176272, 
            27823, 
            0, 
            '5,000,000 .. 10,000,000', 
            1293, 
            366, 
            696, 
            366, 
            29.99, 
            29.99, 
            0, 
            7758);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            1468810, 
            '鬼谷八荒 Tale of Immortal', 
            '鬼谷工作室', 
            '鬼谷工作室, Lightning Games', 
            NULL, 
            117728, 
            105669, 
            0, 
            '10,000,000 .. 20,000,000', 
            3931, 
            60, 
            2279, 
            60, 
            19.99, 
            19.99, 
            0, 
            5500);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            1517290, 
            'Battlefield 2042', 
            'DICE', 
            'Electronic Arts', 
            NULL, 
            122537, 
            151515, 
            0, 
            '10,000,000 .. 20,000,000', 
            2385, 
            230, 
            1176, 
            62, 
            59.99, 
            59.99, 
            0, 
            9599);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            1599340, 
            'Lost Ark', 
            'Smilegate RPG', 
            'Amazon Games', 
            NULL, 
            142960, 
            57510, 
            0, 
            '50,000,000 .. 100,000,000', 
            4364, 
            21, 
            801, 
            39, 
            0.00, 
            0.00, 
            0, 
            16723);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            1623730, 
            'Palworld', 
            'Pocketpair', 
            'Pocketpair', 
            NULL, 
            297196, 
            19765, 
            0, 
            '50,000,000 .. 100,000,000', 
            3192, 
            263, 
            1991, 
            56, 
            29.99, 
            29.99, 
            0, 
            26053);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            1811260, 
            'EA SPORTS FIFA 23', 
            'EA Canada &amp; EA Romania', 
            'Electronic Arts', 
            NULL, 
            85449, 
            65349, 
            0, 
            '10,000,000 .. 20,000,000', 
            10715, 
            1179, 
            4166, 
            1764, 
            0.00, 
            0.00, 
            0, 
            4142);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            1938090, 
            'Call of Duty: Modern Warfare II', 
            'Sledgehammer Games, Treyarch, Infinity Ward, Beenox, Raven Software, High Moon Studios, Demonware', 
            'Activision', 
            NULL, 
            357104, 
            254896, 
            0, 
            '50,000,000 .. 100,000,000', 
            4311, 
            644, 
            378, 
            167, 
            69.99, 
            69.99, 
            0, 
            100062);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            1966720, 
            'Lethal Company', 
            'Zeekerss', 
            'Zeekerss', 
            NULL, 
            417308, 
            11427, 
            0, 
            '10,000,000 .. 20,000,000', 
            1246, 
            195, 
            608, 
            124, 
            9.99, 
            9.99, 
            0, 
            22697);
INSERT INTO steam_games (
            appid, 
            name, 
            developer, 
            publisher, 
            score_rank, 
            positive, 
            negative, 
            userscore, 
            owners, 
            average_forever, 
            average_2weeks, 
            median_forever, 
            median_2weeks, 
            price, 
            initialprice, 
            discount, 
            ccu) VALUES (
            2358720, 
            'Black Myth: Wukong', 
            'Game Science', 
            'Game Science', 
            NULL, 
            709252, 
            30563, 
            0, 
            '50,000,000 .. 100,000,000', 
            1983, 
            1700, 
            1756, 
            1524, 
            59.99, 
            59.99, 
            0, 
            1212446);
